import "./globals.css";
import "@/app/fonts/style.css";
import Header from "./components/header";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fa" dir="rtl">
            <body className="my-10 mx-32 relative">
                <Header />
                {children}
            </body>
        </html>
    );
}
